[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read", path = "./test" }, { access = "read-write", path = "./script/output" }]
optimizer = true
optimizer_runs = 200
solc-version = "0.8.25"
evm_version = "cancun"
verbosity = 4

[fmt]
line_length = 80

[rpc_endpoints]
local = "http://localhost:8545"
holesky = "https://rpc.holesky.ethpandaops.io"
sepolia = "${SEPOLIA_RPC_URL}"
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"
fraxtal_testnet = "https://rpc.testnet.frax.com"

mainnet = "${MAINNET_RPC_URL}"
base = "${BASE_RPC_URL}"
fraxtal = "https://rpc.frax.com"

[etherscan]
sepolia = { key = "${MAINNET_ETHERSCAN_API_KEY}" }
base_sepolia = { key = "${BASESCAN_API_KEY}" }
fraxtal_testnet = { key = "${FRAXSCAN_API_KEY}" }

mainnet = { key = "${MAINNET_ETHERSCAN_API_KEY}" }
base = { key = "${BASESCAN_API_KEY}" }
fraxtal = { key = "${FRAXSCAN_API_KEY}" }
