[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [
    { access = "read", path = "./test" },
    { access = "read-write", path = "./script/output" },
    { access = "read", path = "./config/holesky-operators.json" },
    { access = "read", path = "./config/mainnet-operators.json" },
]
optimizer = true
optimizer_runs = 200
solc-version = "0.8.25"
# NOTE: The evm_version is automatically changed to `shanghai` for *_mantle Makefile scripts because mantle does not support cancun yet
evm_version = "cancun"
verbosity = 4

[fmt]
line_length = 80

[rpc_endpoints]
# used for local development
anvil = "http://localhost:8545"
# used for `dev` environment
holesky_dev = "https://holesky.gateway.tenderly.co"
dev-0 = "https://holesky.gateway.tenderly.co"
dev-1 = "https://holesky.gateway.tenderly.co"
dev-2 = "https://holesky.gateway.tenderly.co"
dev-3 = "https://holesky.gateway.tenderly.co"
# used for `test` environment
holesky = "https://holesky.gateway.tenderly.co"
sepolia = "${SEPOLIA_RPC_URL}"
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"
fraxtal_testnet = "https://rpc.testnet.frax.com"
mantle_sepolia = "https://rpc.sepolia.mantle.xyz"
scroll_sepolia = "https://sepolia-rpc.scroll.io"
# prod environment
mainnet = "${MAINNET_RPC_URL}"
base = "${BASE_RPC_URL}"
fraxtal = "https://rpc.frax.com"
mantle = "https://rpc.mantle.xyz"
polygon_zkevm = "https://zkevm-rpc.com"

[etherscan]
sepolia = { key = "${MAINNET_ETHERSCAN_API_KEY}" }
holesky = { key = "${MAINNET_ETHERSCAN_API_KEY}" }
base_sepolia = { key = "${BASESCAN_API_KEY}" }
fraxtal_testnet = { key = "${FRAXSCAN_API_KEY}" }
mantle_sepolia = { key = "${MANTLESCAN_API_KEY}" }
scroll-sepolia = { key = "${SCROLLSCAN_API_KEY}" }

mainnet = { key = "${MAINNET_ETHERSCAN_API_KEY}" }
base = { key = "${BASESCAN_API_KEY}" }
fraxtal = { key = "${FRAXSCAN_API_KEY}" }
mantle = { key = "${MANTLESCAN_API_KEY}" }
polygon_zkevm = { key = "${POLYGONSCAN_API_KEY}" }
scroll = { key = "${SCROLLSCAN_API_KEY}" }
