[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]
fs_permissions = [
    { access = "read", path = "./test" },
    { access = "read-write", path = "./script/output" },
    { access = "read", path = "./config/holesky-operators.json" },
    { access = "read", path = "./config/mainnet-operators.json" },
]
optimizer = true
optimizer_runs = 4000
solc-version = "0.8.25"
evm_version = "cancun"
verbosity = 4

[fmt]
line_length = 80

[rpc_endpoints]
# used for local development
anvil = "http://localhost:8545"
# used for `dev` environment
dev-0 = "https://ethereum-holesky-rpc.publicnode.com"
dev-1 = "https://ethereum-holesky-rpc.publicnode.com"
dev-2 = "https://ethereum-holesky-rpc.publicnode.com"
dev-3 = "https://ethereum-holesky-rpc.publicnode.com"
# used for `test` environment
holesky = "https://ethereum-holesky-rpc.publicnode.com"
sepolia = "https://ethereum-sepolia-rpc.publicnode.com"
base_sepolia = "https://base-sepolia-rpc.publicnode.com"
fraxtal_testnet = "https://rpc.testnet.frax.com"
mantle_sepolia = "https://rpc.sepolia.mantle.xyz"
scroll_sepolia = "https://sepolia-rpc.scroll.io"
hoodi = "https://0xrpc.io/hoodi"
# prod environment
mainnet = "https://ethereum-rpc.publicnode.com"
base = "https://base-rpc.publicnode.com"
fraxtal = "https://rpc.frax.com"
mantle = "https://rpc.mantle.xyz"
polygon_zkevm = "https://zkevm-rpc.com"
bsc = "https://bsc-rpc.publicnode.com"
arbitrum = "https://arbitrum-one-rpc.publicnode.com"
optimism = "https://optimism-rpc.publicnode.com"
polygon = "https://polygon-bor-rpc.publicnode.com"
scroll = "https://scroll-rpc.publicnode.com"
cronos = "https://cronos-evm-rpc.publicnode.com"
gnosis = "https://rpc.gnosischain.com"
berachain = "https://rpc.berachain.com"

[dependencies]
"@openzeppelin-contracts-upgradeable" = "5.2.0"
"@openzeppelin-contracts" = "5.2.0"
"@layerzerolabs-lz-evm-protocol-v2" = "3.0.84"
"@layerzerolabs-oapp-evm" = "0.3.2"
"@layerzerolabs-oft-evm" = "3.1.3"
