name: Forge

on: push

env:
  FOUNDRY_PROFILE: ci

jobs:
  coverage:
    strategy:
      fail-fast: true

    runs-on: ubuntu-22.04
    
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable

      - name: Install dependencies
        run: forge soldeer install
        id: install-dependencies

      - name: Install LCOV
        uses: hrishikesh-kadam/setup-lcov@f5da1b26b0dcf5d893077a3c4f29cf78079c841d # v1.0.0

      - name: Generate coverage report
        run: make coverage-report
        id: coverage

      - name: Report code coverage
        uses: zgosalvez/github-actions-report-lcov@a546f89a65a0cdcd82a92ae8d65e74d450ff3fbc # v4.1.4
        with:
          # update-comment: true TODO - add access token so that action can comment with coverage report
          coverage-files: lcov.info
          minimum-coverage: 8
