name: Forge

on: push

env:
  FOUNDRY_PROFILE: ci

jobs:
  fmt:
    strategy:
      fail-fast: true

    runs-on: ubuntu-22.04
    
    steps:
      - uses: actions/checkout@v4

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable

      - name: Install dependencies
        run: forge soldeer install
        id: install-dependencies
    
      - name: Run forge fmt
        run: forge fmt --check
        id: fmt
