name: Slither

on: push

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable

      - name: Install Soldeer Dependencies
        run: forge soldeer install

      - name: Compile Contracts
        # slither requires --build-info to be present in the build output
        run: forge build --build-info --skip */test/** */script/**

      - name: Run Slither
        uses: crytic/slither-action@v0.4.1
        id: slither
        with:
          fail-on: high
          ignore-compile: true
